#!/bin/sh

### BEGIN INIT INFO

### END INIT INFO

ROOT_PATH=/home/ziwei/workspace/KompicsSRE/deployment/
SRE_JAR=SRE-Kompics.jar
SRE_CONFIG=SREEnv.config

RESPONSE="000"

sendReqeust(){
RESPONSE=$(curl --write-out %{http_code} --silent --output /dev/null "http://localhost:8080/SRE/log")
}

case "$1" in
  start)
	sendReqeust
	if [ "$RESPONSE" -eq "000" ] || [ "$RESPONSE" -eq "404" ]
	then
		export JAVA_OPTS="-D custom.logging.root=$ROOT_PATH"
		java -jar "$ROOT_PATH$SRE_JAR" "$ROOT_PATH" "$SRE_CONFIG" &
		echo "starting"
		sleep 2
		sendReqeust
		if [ "$RESPONSE" -ne "000" ] && [ "$RESPONSE" -ne "404" ]
		then
			echo "started successfully"
		else
			echo "cannot start"
		fi
	else
		echo "already running"
	fi
	;;
  stop)
	curl "http://localhost:8080/SRE/stop" --silent --output /dev/null
	sleep 2
	sendReqeust
	if [ "$RESPONSE" -eq "000" ] || [ "$RESPONSE" -eq "404" ]
	then
		echo "shut down successfully"
	fi
	;;
  restart)
  	$0 stop
	sleep 3
	$0 start
	;;
  status)
	sendReqeust
	if [ "$RESPONSE" -eq "000" ] || [ "$RESPONSE" -eq "404" ]
	then
		echo "not running"
	else
		echo "it is running"
	fi
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|status}" >&2
	exit 1
	;;
esac

