#!/bin/sh

### BEGIN INIT INFO

### END INIT INFO

ROOT_PATH=/srv/SRE-Kompics/
SRE_JAR=KompicsSRE.jar

RESPONSE="000"
URL="http://localhost:8000/SRE/"

sendReqeust(){
RESPONSE=$(curl --write-out %{http_code} --silent --output /dev/null "$URL""log")
}

case "$1" in
  start)
	sendReqeust
	if [ "$RESPONSE" -eq "000" ] || [ "$RESPONSE" -eq "404" ]
	then
		export JAVA_OPTS="-D SRERootPath=$ROOT_PATH"
		java -jar "$ROOT_PATH$SRE_JAR" &
		echo "starting"
		sleep 2
		sendReqeust
		if [ "$RESPONSE" -ne "000" ] && [ "$RESPONSE" -ne "404" ]
		then
			echo "started successfully"
		else
			echo "cannot start"
		fi
	else
		echo "already running"
	fi
	;;
  stop)
	curl "$URL""stop" --silent --output /dev/null
	sleep 2
	sendReqeust
	if [ "$RESPONSE" -eq "000" ] || [ "$RESPONSE" -eq "404" ]
	then
		echo "shut down successfully"
	fi
	;;
  restart)
  	$0 stop
	sleep 3
	$0 start
	;;
  status)
	sendReqeust
	if [ "$RESPONSE" -eq "000" ] || [ "$RESPONSE" -eq "404" ]
	then
		echo "not running"
	else
		echo "it is running"
	fi
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|status}" >&2
	exit 1
	;;
esac

